// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flluxylfscixfeyonxsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsbHV4eWxmc2NpeGZleW9ueHNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzcxNzYsImV4cCI6MjA2MDcxMzE3Nn0.e50WWaRU7Pmwgycf1Xnk4FMweqJKJ4MTFCht8qquCEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);